/** Plastic colour grades used when sorting scrap into usable streams. */
export const SORT_COLORS = [
  { code: 'WHITE', name: 'White' },
  { code: 'CLEAR', name: 'Clear / natural' },
  { code: 'TRANSPARENT', name: 'Transparent' },
  { code: 'RED', name: 'Red' },
  { code: 'PINK', name: 'Pink' },
  { code: 'ORANGE', name: 'Orange' },
  { code: 'YELLOW', name: 'Yellow' },
  { code: 'GREEN', name: 'Green' },
  { code: 'LIGHT_GREEN', name: 'Light green' },
  { code: 'BLUE', name: 'Blue' },
  { code: 'LIGHT_BLUE', name: 'Light blue' },
  { code: 'DARK_BLUE', name: 'Dark blue' },
  { code: 'PURPLE', name: 'Purple' },
  { code: 'VIOLET', name: 'Violet' },
  { code: 'BROWN', name: 'Brown' },
  { code: 'GREY', name: 'Grey' },
  { code: 'SILVER', name: 'Silver' },
  { code: 'GOLD', name: 'Gold' },
  { code: 'BLACK', name: 'Black' },
  { code: 'MULTICOLOR', name: 'Multicolor' },
  { code: 'MIXED', name: 'Mixed / other' },
] as const
